version: '3.7'

services:
  database:
    build: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_db:/var/lib/postgresql/data/
    restart:
      - always
  
  pgadmin:
    image: dpage/pgadmin4:7.8
    environment:
      PGADMIN_DEFAULT_EMAIL: amdin@mail.com
      PGADMIN_DEFAULT_PASSWORD: P@ssw0rd
    ports:
      - 8000:80
    depends_on:
      - database
    restart:
      - always

volumes:
  postgres_db: